
const DIRECTION = require('../DIRECTION/DIRECTION');

// Z ist "UP" - Dimension | Right-Handed Coordinate System

const ORTHOGONAL_DIRECTIONS = [
    [DIRECTION.POSITIVE_Y, DIRECTION.POSITIVE_X], // -z
    [DIRECTION.POSITIVE_X, DIRECTION.POSITIVE_Z], // -y
    [DIRECTION.POSITIVE_Z, DIRECTION.POSITIVE_Y], // -x

    [DIRECTION.POSITIVE_Z, DIRECTION.POSITIVE_Y], // x
    [DIRECTION.POSITIVE_X, DIRECTION.POSITIVE_Z], // y
    [DIRECTION.POSITIVE_Y, DIRECTION.POSITIVE_X], // z
];

module.exports = ORTHOGONAL_DIRECTIONS;